modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="memesprojectdiscforge"
version="0.0.1Alpha"
displayName="MemesProjectDisc-Forge"
credits="Created using mod maker MCreator"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Tex, TexStudio,MCreator"

[[dependencies.memesprojectdiscforge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




