/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.texstudio.memesprojectdiscforge;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class MemesprojectdiscforgeModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public MemesprojectdiscforgeModElements() {
		sounds.put(new ResourceLocation("memesprojectdiscforge", "abiding_chills"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "abiding_chills")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "ad_oblivione"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "ad_oblivione")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "chattering_snowflakes"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "chattering_snowflakes")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "finale_of_the_snowtomb"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "finale_of_the_snowtomb")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "fragile_antasy"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "fragile_antasy")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "glistening_shards"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "glistening_shards")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "in_the_desolate_hallway"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "in_the_desolate_hallway")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "menacing_cove"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "menacing_cove")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "moonlike_smile"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "moonlike_smile")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "once-colored_memories"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "once-colored_memories")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "serene_and_sweet_adieu"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "serene_and_sweet_adieu")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "sinister_mist"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "sinister_mist")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "snow-buried_tales"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "snow-buried_tales")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "spin_of_ice_crystals"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "spin_of_ice_crystals")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "striding_in_the_snowstorm"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "striding_in_the_snowstorm")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "the_flourishing_past"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "the_flourishing_past")));
		sounds.put(new ResourceLocation("memesprojectdiscforge", "unfinished_frescoes"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("memesprojectdiscforge", "unfinished_frescoes")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("memesprojectdiscforge").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == MemesprojectdiscforgeModElements.ModElement.class)
						elements.add((MemesprojectdiscforgeModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(MemesprojectdiscforgeModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		MemesprojectdiscforgeMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final MemesprojectdiscforgeModElements elements;
		protected final int sortid;
		public ModElement(MemesprojectdiscforgeModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
